name: Build and release client files
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: windows-latest

    steps:
      - name: Check out selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '4.7.2'
      
      - name: Restore NuGet packages
        run: nuget restore LiveResults.Client.sln
       
      - name: Build and publish solution
        run: dotnet publish LiveResults.Client.sln -c Release -o published

      - name: Collect binaries
        run: |
          mkdir package
          copy published\*.exe package\
          copy published\LiveResuls.Model.dll package\
          copy published\MySql.Data.dll package\
          copy published\Newtonsoft.Json.dll package\

      - name: Zip binaries (flat, with date)
        shell: pwsh
        run: |
          $date = Get-Date -Format "yyyy-MM-dd"
          $zipName = "LiveResClient_$date.zip"
          $packagePath = "$env:GITHUB_WORKSPACE\package"
          if (Test-Path $zipName) { Remove-Item $zipName }
          if (-Not (Test-Path $packagePath)) { Write-Error "Package folder not found: $packagePath" }
          Compress-Archive -Path (Get-ChildItem $packagePath) -DestinationPath $zipName
          Add-Content -Path $env:GITHUB_ENV -Value "ZIP_NAME=$zipName"
          
      - name: Upload ZIP to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact (manual run only)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: ${{ env.ZIP_NAME }}





            
