name: Build client files

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          submodules: recursive

      - name: Set up MS Build
        uses: microsoft/setup-msbuild@v2
      
      - name: Restore NuGet packages
        run: nuget restore LiveResults.Client.sln
       
      - name: Build repo
        run: msbuild LiveResults.Client.sln /p:Configuration=Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: build.output
          path: |
            **\bin\Release\*.exe
            **\bin\Release\LiveResuls.Model.dll
            **\bin\Release\MySql.Data.dll
            **\bin\Release\Newtonsoft.Json.dll
            
