name: Build and release client files
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'

jobs:
  build-and-upload:
    runs-on: windows-latest

    steps:
      - name: Check out selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          submodules: recursive

      - name: Set up MS Build
        uses: microsoft/setup-msbuild@v2
      
      - name: Restore NuGet packages
        run: nuget restore LiveResults.Client.sln
       
      - name: Build solution
        run: msbuild LiveResults.Client.sln /p:Configuration=Release

      - name: Collect binaries
        run: |
          mkdir package
          copy **\bin\Release\*.exe package\
          copy ***\bin\Release\LiveResuls.Model.dll package\
          copy ***\bin\Release\MySql.Data.dll package\
          copy ***\bin\Release\Newtonsoft.Json.dllpackage\

      - name: Zip binaries (flat)
        run: powershell Compress-Archive -Path package\* -DestinationPath build.zip

      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v2
        with:
          files: build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





            
